spring.application.name=anoto-api
server.port=8080

# Supabase
spring.datasource.url=jdbc:postgresql://db.pglxtxqbmsosksgsjhma.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Oellagem1600
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=anoto-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG

# Debug
logging.level.org.springframework.security=DEBUG
