version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: anoto
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Oellagem1600
      POSTGRES_DB: anoto
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: local-pgadminanoto
    restart: always
    ports:
      - "8081:80"  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  postgres_data: